stages:
  - style
  - test

pep8:
  stage: style
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e pep8
  tags:
    - default
  
unittest-py2.7:
  stage: test
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e unittest-py2.7
  tags:
    - default

unittest-py3.4:
  stage: test
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e unittest-py3.4
  tags:
    - default
