stages:
  - style
  - test
  - deploy

pep8:
  stage: style
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e pep8
  tags:
    - python2.7
  
unittest-py2.7:
  stage: test
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e py27
  tags:
    - python2.7

unittest-py3.4:
  stage: test
  script:
    - pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tox
    - tox -e py34
  tags:
    - python3.4


docker-deploy:
  stage: deploy
  script: 
    - docker build -t flask-demo:latest .
    - if [ $(docker ps -qa --filter name=flask-web-demos-xue) ];then docker rm -f flask-web-demos-xue;fi
    - docker run -d --name flask-web-demos-xue -p 15000:5000 flask-demo:latest
  tags:
    - default